# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build and package
      run: |
        VERSION=$(date +"%Y.%m.%d.%H")
        dotnet pack -p:PackageVersion=$VERSION -c Release
    - name: Deploy
      if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
      run: |
        dotnet nuget add source "${{ github.server_url }}/projects/${{ github.repository }}/packages/nuget/index.json" --name github --username github-actions --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
        dotnet nuget push "./Nexus.Token.SDK/bin/Release/*.nupkg" --source github
        dotnet nuget push "./Nexus.SDK.Shared/bin/Release/*.nupkg" --source github
        dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
